id: AAB666744
base_file: f7E45.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:17:25.280302
  last_modified_at: 2022-06-15 20:17:25.280328
